### ISSUE TITLE
Null error with LetterViewerMenu (Adventure Guild)

### ISSUE THREAD

**Issue by GenDeathrow** [Stardew-Valley-Modding/Bookcase#6]
Bookcase version: 0.7.2

Seems to be an issue when you try to enter the adventures guild.Its right after you click on the door. 
But its only before you finish the 'Initiation Quest' of killing 10 slime's. It will show whats looks like a blank letter and than it throws this error in SMAPI.

https://gist.github.com/GenDeathrow/bd3291d7717f0167736360c550d23892

Also I noticed when you get inside the adventure guild the poster board on the wall will also cause the same crash to happen.

**Comment by GenDeathrow** [comment]
I didn't like the title..

**Comment by Darkhax** [comment]
Imagine taking 2 years to fix a simple NPE, that would be embarassing 😆

**Comment by GenDeathrow** [comment]
lol @Darkhax
