### ISSUE TITLE
Hoping for an update! 

### ISSUE THREAD

**Issue by Darkosto** [Stardew-Valley-Modding/Bookcase#7]
Heya! Are you considering updating this to the new version? I'd love to do a new playthrough with mods and integration :)

Thank you!!!

**Comment by Darkhax** [comment]
That's a funny coincidence. Jared recently finished up his new build pipeline for SDV mods which should make it easier for both of us to maintain our SDV mods. It will be a few weeks before I can put this into action though, have a lot of house keeping to get through first.

**Comment by Darkhax** [comment]
Oh right, updated this ages ago.
